model:
    _target_: asteroid.DCCRNet
    architecture: "DCCRN-CL"
    stft_n_filters: 2048
    stft_kernel_size: 2048
    stft_stride: 1024
    
dset:
    mixture_train:
        repeat_factor: 30

model_version: 'stft2048'
reduce_lr_patience: 5