model:
    _target_: asteroid.DCCRNet
    architecture: "DCCRN-CL"
    stft_n_filters: 1024
    stft_kernel_size: 1024
    stft_stride: 512
    
dset:
    mixture_train:
        repeat_factor: 30

model_version: 'stft1024'
reduce_lr_patience: 5