model:
    _target_: asteroid.DCUNet
    architecture: "DCUNet-20"
    stft_n_filters: 2048
    stft_kernel_size: 2048
    stft_stride: 1024
    fix_length_mode: "pad"
    
dset:
    mixture_train:
        repeat_factor: 30

model_version: 'stft2048'
reduce_lr_patience: 5