model:
    _target_: asteroid.DCUNet
    architecture: "DCUNet-20"
    fix_length_mode: "pad"
    
dset:
    mixture_train:
        repeat_factor: 30
        snr_range: [-5, 15]

model_version: 'snr5_15'
reduce_lr_patience: 5