model:
    _target_: asteroid.SMoLnet
    
dset:
    timit: ${env:HOME}/datasets/TIMIT_16khz
    noises: ${env:HOME}/datasets/noises_16khz
    
sample_rate: 16000
model_version: '16khz'

loss: "mse"
lr: 1e-4
crop_length: 10240