model:
    _target_: asteroid.WaveUNet

dset:
    timit: ${env:HOME}/datasets/TIMIT_16khz
    noises: ${env:HOME}/datasets/noises_16khz
    
    mixture_train:
        repeat_factor: 30
    
sample_rate: 16000
model_version: '16khz'
loss: "mse"
crop_length: 16384